/* Ground OPS Tracker service worker.
 * - App shell is precached (list generated by tools/build-pwa.js into precache-manifest.js).
 * - API calls (cross-origin POST to Apps Script), map tiles and anything non-GET are NEVER intercepted or cached,
 *   so attendance can never be "confirmed" from a cache.
 * - Navigations: network first, fall back to the cached shell => the app opens offline.
 * - config.js: network first (so a changed API_URL takes effect), cached copy as fallback.
 * - Other same-origin GETs: cache first + background refresh. */
importScripts('./precache-manifest.js');
const CACHE = `gops-${self.GOPS_PRECACHE.version}`;
const SHELL = self.GOPS_PRECACHE.files;

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('gops-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('message', (event) => { if (event.data === 'SKIP_WAITING') self.skipWaiting(); });

const timeout = (ms) => new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), ms));
async function networkFirst(req, fallbackUrl) {
  const cache = await caches.open(CACHE);
  try {
    const res = await Promise.race([fetch(req), timeout(5000)]);
    if (res && res.ok && req.method === 'GET') cache.put(req, res.clone());
    return res;
  } catch (e) {
    return (await cache.match(req, { ignoreSearch: true })) || (fallbackUrl && (await cache.match(fallbackUrl))) || Response.error();
  }
}
async function staleWhileRevalidate(req) {
  const cache = await caches.open(CACHE), hit = await cache.match(req, { ignoreSearch: true });
  const refresh = fetch(req).then((res) => { if (res && res.ok) cache.put(req, res.clone()); return res; }).catch(() => null);
  return hit || (await refresh) || Response.error();
}
self.addEventListener('fetch', (event) => {
  const req = event.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/service-worker.js') || url.pathname.endsWith('/precache-manifest.js')) return;
  if (req.mode === 'navigate') { event.respondWith(networkFirst(req, url.pathname.endsWith('admin.html') ? './admin.html' : './index.html')); return; }
  if (url.pathname.endsWith('/config.js')) { event.respondWith(networkFirst(req)); return; }
  event.respondWith(staleWhileRevalidate(req));
});
